site_name: POG.network
site_url: "https://pog.network"
docs_dir: "www"
edit_uri: ""

copyright: "&copy pog.network 2021"

nav:
  - Home: "README.md"
  - Specification: "!include ./projects/specification/mkdocs.yml"
  - Documentation:
      - Champ: "!include ./projects/champ/mkdocs.yml"

plugins:
  - monorepo
  - search
  - mermaid2:
      arguments:
        theme: "dark"

theme:
  name: "material"
  logo: assets/pog.svg
  custom_dir: overrides
  font:
    text: Quicksand
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tabs.sticky
    - navigation.expand
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/mermaid@8.7.0/dist/mermaid.min.js
  - assets/index.js

markdown_extensions:
  - admonition
  - footnotes
  - meta
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
      toc_depth:
        3
        # repo_url: https://github.com/pognetwork/champ
        # repo_name: pognetwork/champ

        # extra:
        #   social:
        #     - icon: fontawesome/brands/github
        #       link: https://github.com/pognetwork/champ
        #       name: Github

repo_url: https://github.com/pognetwork/champ
repo_name: pognetwork/champ

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pognetwork/champ
      name: Github
