site_name: POG.network
site_url: "https://pog.network"
docs_dir: "www"
edit_uri: ""

nav:
  - Intro: "README.md"
  - Specification: "!include ./projects/specification/mkdocs.yml"
  - Documentation:
      - Champ: "!include ./projects/champ/mkdocs.yml"

plugins:
  - monorepo
  - search

theme:
  name: "material"
  logo: assets/pog.svg
  custom_dir: overrides
  font:
    text: Quicksand
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tabs.sticky
    - navigation.expand
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - meta
  - pymdownx.details
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
      toc_depth:
        3
        # repo_url: https://github.com/pognetwork/champ
        # repo_name: pognetwork/champ

        # extra:
        #   social:
        #     - icon: fontawesome/brands/github
        #       link: https://github.com/pognetwork/champ
        #       name: Github

repo_url: https://github.com/pognetwork/champ
repo_name: pognetwork/champ

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pognetwork/champ
      name: Github
